
'use strict';
// This is a self-contained interaction prototype, not a security assessment.
// All records, priority assignments, exposure and decisions below are synthetic.
// No network APIs, external scripts, fonts, AI tools or ticket creation are used.
const DEMO_NOW=new Date('2026-09-19T10:00:00Z');
const STORE_KEY='ptv-triage-precision-demo-v1';
const I={search:'<svg class="icon-svg" viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>',arrow:'<svg class="icon-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>',close:'<svg class="icon-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>',expand:'<svg class="icon-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/></svg>',filter:'<svg class="icon-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M7 12h10M10 18h4"/></svg>'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cap=s=>s==='prod'?'Production':s[0].toUpperCase()+s.slice(1);
const e=(type,date,description)=>({type,date,description});
function scope(id,team,env,status='needs_review',exposure='Unknown',stale=false){return{id,team,env,status,observation:status==='not_observed'?'not_observed':status==='verified'?'verified_remediated':'observed',exposure,stale,service:({data:'search-service',alpha:'api-gateway',beta:'customer-web',platform:'build-platform',unassigned:'unmapped-worker'})[team],observed:stale?'2026-09-09T06:00:00Z':'2026-09-19T09:42:00Z',reason:'',owner:'',due:'2026-09-26',suppressed:false};}
function advisory(n,pkg,severity,priority,scopes,opts={}){let id=`DEMO-2026-${String(n).padStart(3,'0')}`;return{id,pkg,severity,priority,scopes,first:'2026-08-24T06:00:00Z',fix:true,kev:'Unknown',due:'2026-09-26',events:[e('new','2026-08-24T06:00:00Z','First recorded observation'),e('observed','2026-09-09T06:00:00Z','Observed in sample import')],...opts};}
const initial=[
 advisory(1,'log4j-core','Critical',1,[scope('s01','data','prod','needs_review','Internet'),scope('s02','data','staging','needs_review','Unknown')],{kev:'Listed (sample)',due:'2026-09-17',first:'2026-08-15T06:00:00Z',events:[e('new','2026-08-15T06:00:00Z','First recorded observation'),e('observed','2026-09-09T06:00:00Z','Observed in sample import'),e('observed','2026-09-19T09:42:00Z','Observed in latest sample import')]}),
 advisory(2,'chromium','Critical',1,[scope('s03','beta','prod','needs_review','Internet')],{kev:'Listed (sample)',due:'2026-09-18',first:'2026-09-09T06:00:00Z',events:[e('new','2026-09-09T06:00:00Z','First recorded observation'),e('observed','2026-09-19T09:42:00Z','Observed in latest sample import')]}),
 advisory(3,'libssl','High',1,[scope('s04','alpha','prod','planned','Internet')],{kev:'Listed (sample)',due:'2026-09-18',events:[e('new','2026-08-24T06:00:00Z','First recorded observation'),e('requested','2026-09-10T09:00:00Z','Remediation plan recorded locally')]}),
 advisory(4,'grpc','Critical',2,[scope('s05','alpha','prod'),scope('s06','alpha','staging','needs_review','Internal')],{due:'2026-09-22'}),
 advisory(5,'systemd','Critical',2,[scope('s07','beta','prod','investigating','Unknown',true)],{fix:false,due:'2026-09-22'}),
 advisory(6,'n8n','High',2,[scope('s08','alpha','prod','needs_review','Internet')],{first:'2026-09-09T06:00:00Z',events:[e('new','2026-09-09T06:00:00Z','First recorded observation')]}),
 advisory(7,'zlib','High',2,[scope('s09','alpha','prod'),scope('s10','beta','staging','needs_review','Unknown',true)],{reopened:true,due:'2026-09-20',events:[e('new','2026-08-24T06:00:00Z','First recorded observation'),e('absent','2026-08-27T06:00:00Z','Not observed in a comparable sample scan; repair not verified'),e('reobserved','2026-09-09T06:00:00Z','Observed again in sample inventory')]}),
 advisory(8,'curl','High',2,[scope('s11','platform','prod','planned','Internal')]),
 advisory(9,'libxml2','High',2,[scope('s12','data','prod','verification','Internal')],{events:[e('new','2026-08-24T06:00:00Z','First recorded observation'),e('requested','2026-09-12T14:00:00Z','Verification requested; current observation state unchanged')]}),
 advisory(10,'argo-workflows','Critical',2,[{...scope('s13','platform','prod'),suppressed:true}],{fix:false,events:[e('new','2026-08-28T06:00:00Z','First recorded observation with scanner suppression; approver and decision date unknown')]}),
 advisory(11,'nodejs','Medium',3,[{...scope('s14','alpha','prod','accepted','Internal'),due:'2026-09-23',reason:'Sample time-limited exception',owner:'Demo operator'}],{events:[e('new','2026-08-24T06:00:00Z','First recorded observation'),e('accepted','2026-09-12T11:00:00Z','Risk accepted for a specific scope until 23 Sep, sample operator')]}),
 advisory(12,'openssl','High',2,[scope('s15','beta','prod')]),
 advisory(13,'rsync','Low',3,[{...scope('s16','data','staging','accepted','Internal'),due:'2026-09-22',reason:'Sample time-limited exception',owner:'Demo operator'}]),
 advisory(14,'busybox','Medium',3,[scope('s17','unassigned','prod')],{fix:false}),
 advisory(15,'traefik','High',2,[scope('s18','platform','prod','not_observed','Unknown')],{events:[e('new','2026-08-24T06:00:00Z','First recorded observation'),e('absent','2026-08-26T06:00:00Z','Not observed in comparable sample scan; no remediation evidence')]}),
 advisory(16,'unbound','Medium',3,[scope('s19','platform','prod','verified','Internal')],{events:[e('new','2026-08-24T06:00:00Z','First recorded observation'),e('verified','2026-09-14T08:30:00Z','Remediation verified against sample deployment and scan evidence')]}),
 advisory(17,'mongodb-c-driver','Low',3,[scope('s20','data','prod','planned','Internal')]),
 advisory(18,'git','High',2,[scope('s21','alpha','prod')],{first:'2026-09-09T06:00:00Z',events:[e('new','2026-09-09T06:00:00Z','First recorded observation')]}),
 advisory(19,'pip','Medium',3,[scope('s22','unassigned','staging','investigating','Unknown',true)],{fix:false}),
 advisory(20,'libpng','Medium',3,[scope('s23','beta','prod','needs_review','Internal')])
];
for(const r of initial){for(const ev of r.events)ev.scope_ids=r.scopes.map(s=>s.id);}
let records=structuredClone(initial),drafts={},audit=[];
let storageOK=true;try{const saved=JSON.parse(localStorage.getItem(STORE_KEY)||'null');if(saved&&saved.version===1){records=saved.records;drafts=saved.drafts||{};audit=saved.audit||[]}}catch(err){storageOK=false}
const state={page:'overview',team:'all',env:'all',query:'',severity:'all',inventoryView:'active',queueView:'needs_review',selected:null,checked:new Set(),inspectorId:null,inspectorTab:'summary',weeks:12,timelineTab:'tracks',eventFilter:'all',sort:'priority',compact:false,queueShown:false};
const statusLabel={needs_review:'Needs decision',investigating:'Investigating',planned:'Remediation planned',verification:'Needs verification',accepted:'Risk accepted',not_observed:'Not observed',verified:'Verified remediated'};
const activeScope=s=>s.observation? !['not_observed','verified_remediated'].includes(s.observation):!['not_observed','verified'].includes(s.status);
const attentionScope=s=>['needs_review','investigating'].includes(s.status);
const scopeMatch=s=>(state.team==='all'||s.team===state.team)&&(state.env==='all'||s.env===state.env);
const visibleScopes=r=>r.scopes.filter(scopeMatch);
const relevant=()=>records.filter(r=>visibleScopes(r).length);
const active=()=>relevant().filter(r=>visibleScopes(r).some(activeScope));
const needs=()=>relevant().filter(r=>visibleScopes(r).some(attentionScope));
const urgent=()=>active().filter(r=>r.priority===1);
const age=r=>Math.floor((DEMO_NOW-new Date(r.first))/86400000);
const shortDate=d=>new Date(d).toLocaleDateString('en-GB',{day:'2-digit',month:'short',timeZone:'UTC'});
const dateTime=d=>new Date(d).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC'})+' UTC';
const severityBadge=s=>`<span class="badge ${s.toLowerCase()}">${esc(s)}</span>`;
const priorityBadge=r=>`<span class="badge p${r.priority}">P${r.priority}${r.priority===1?' · Now':''}</span>`;
const labelState=s=>`<span class="state ${s==='needs_review'?'blue':s==='accepted'?'amber':s==='verified'?'green':''}"><span class="state-dot" style="background:currentColor"></span>${statusLabel[s]||esc(s)}</span>`;
function aggregateState(scopes){let statuses=[...new Set(scopes.map(s=>s.status))];return statuses.length===1?labelState(statuses[0]):'<span class="state">Mixed · '+statuses.length+' states</span>'}
function saveStorage(){try{localStorage.setItem(STORE_KEY,JSON.stringify({version:1,records,drafts,audit}));storageOK=true}catch(err){storageOK=false}document.getElementById('storageState').textContent=storageOK?'Demo edits saved in this browser':'Session only · browser storage unavailable'}
function toast(text){let el=document.getElementById('toast');el.textContent=text;el.className='toast';el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4200)}
function updateURL(){const p=new URLSearchParams({page:state.page});if(state.team!=='all')p.set('team',state.team);if(state.env!=='all')p.set('env',state.env);if(state.selected&&state.page==='review')p.set('item',state.selected);try{history.replaceState(null,'','#'+p.toString())}catch{}}
function render(){
 const focusBefore=document.activeElement;const focusID=focusBefore?.id;const focusData=focusBefore?.dataset?{...focusBefore.dataset}:null;
 document.body.classList.toggle('compact',state.compact);
 document.getElementById('teamFilter').value=state.team;document.getElementById('envFilter').value=state.env;
 document.getElementById('nav').innerHTML=[['overview','Overview'],['inventory','Vulnerabilities'],['review','Review'],['timeline','Timeline']].map(([p,label])=>`<button data-action="nav" data-page="${p}" class="${state.page===p?'active':''}" ${state.page===p?'aria-current="page"':''}>${label}${p==='review'?'<span class="nav-count">'+needs().length+'</span>':''}</button>`).join('');
 const main=document.getElementById('main');main.className='page '+(state.page==='inventory'?'inventory-page':state.page==='review'?'review-page'+(state.queueShown?' show-queue':''):state.page==='timeline'?'timeline-page':'');
 main.innerHTML=({overview:renderOverview,inventory:renderInventory,review:renderReview,timeline:renderTimeline})[state.page]();
 if(state.page==='review')updateScopeCount();
 saveStorage();updateURL();
 if(focusBefore&&focusBefore!==document.body&&!focusBefore.isConnected){let target=focusID?document.getElementById(focusID):null;if(!target&&focusData?.action){let selector='[data-action="'+CSS.escape(focusData.action)+'"]';for(const key of ['page','id','view','tab','team'])if(focusData[key])selector+='[data-'+key+'="'+CSS.escape(focusData[key])+'"]';target=document.querySelector(selector);}if(target&&target.getClientRects().length)target.focus({preventScroll:true});}
}
function metric(label,value,sub,action,cls=''){return `<button class="metric ${cls}" data-action="${action}"><span class="metric-label">${label}<span aria-hidden="true">↗</span></span><span class="value ${cls==='alert-top'?'red':''}">${value}</span><span class="sub">${sub}</span></button>`}
function renderOverview(){
 const a=active(),n=needs(),u=urgent(),as=a.flatMap(r=>visibleScopes(r).filter(activeScope));const unknown=as.filter(s=>s.exposure==='Unknown'),stale=as.filter(s=>s.stale);const expires=as.filter(s=>s.status==='accepted'&&new Date(s.due+'T23:59:59Z')-DEMO_NOW<7*86400000);const unassigned=as.filter(s=>s.team==='unassigned');
 const title=u.length?'Immediate attention required':n.length?'Review is required':'No unreviewed items in this scope';
 const teams=['data','alpha','beta','platform','unassigned'].filter(t=>state.team==='all'||state.team===t).map(t=>{let rs=a.filter(r=>visibleScopes(r).some(s=>s.team===t&&activeScope(s)));let critical=rs.filter(r=>r.severity==='Critical').length;let todo=rs.filter(r=>visibleScopes(r).some(s=>s.team===t&&attentionScope(s))).length;let unknownCount=rs.flatMap(r=>visibleScopes(r).filter(s=>s.team===t&&activeScope(s)&&s.exposure==='Unknown')).length;return{team:t,rs,critical,todo,unknownCount}}).sort((x,y)=>y.critical-x.critical||y.todo-x.todo);
 return `<div class="page-head"><div><h1>Security overview</h1><p>Latest recorded deployment state · all totals follow the scope above.</p></div><div class="row"><button data-action="data-health">Evidence health</button><button class="primary" data-action="start-review">Start review ${I.arrow}</button></div></div>
 <section class="callout ${u.length?'':'caution'}" aria-label="Attention and evidence confidence"><div class="symbol">!</div><div class="grow"><h2>${title}</h2><p>${u.length} P1 CVEs in this scope${u.length?' · '+u.filter(r=>new Date(r.due)<DEMO_NOW).length+' past their sample response deadline':''}. Priority is not a claim of compromise.</p></div><div class="confidence"><strong>Confidence: limited</strong><br><span class="muted">${unknown.length} unknown-exposure scopes · ${stale.length} stale scopes</span></div><button class="quiet" data-action="policy">Why this priority? ↗</button></section>
 <div class="metrics" aria-label="Current scoped totals">${metric('Active CVEs',a.length,`${as.length} open scopes · latest known state`,'active-inventory')}${metric('Need a decision',n.length,'Distinct CVEs · investigation included','start-review')}${metric('Immediate priority',u.length,'P1 · explainable sample policy','urgent-inventory','alert-top')}${metric('Exposure unknown',unknown.length,'Affected scopes · evidence needed','unknown-inventory','warn-top')}</div>
 <div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>Ownership by team</h2><p>Who needs to act, not just who has findings.</p></div><span class="tag">Active CVEs</span></div><div class="table-wrap"><table class="data-table"><caption class="sr-only">Team vulnerability ownership, filtered by shared scope</caption><thead><tr><th>Team</th><th>Active</th><th>Critical</th><th>Needs decision</th><th>Exposure unknown</th><th><span class="sr-only">Action</span></th></tr></thead><tbody>${teams.map(t=>`<tr><td><div class="row"><span class="team-icon">${t.team==='unassigned'?'?':t.team.slice(0,2).toUpperCase()}</span><span class="team-name">${cap(t.team)}</span></div></td><td class="num"><strong>${t.rs.length}</strong></td><td class="num ${t.critical?'red':'muted'}">${t.critical}</td><td class="num"><button class="link" data-action="team-review" data-team="${t.team}">${t.todo}</button></td><td class="num ${t.unknownCount?'amber':'muted'}">${t.unknownCount} ${t.unknownCount===1?'scope':'scopes'}</td><td><button class="icon quiet" data-action="team-inventory" data-team="${t.team}" aria-label="View ${cap(t.team)} vulnerabilities">${I.arrow}</button></td></tr>`).join('')}</tbody></table></div><div class="panel-foot"><span>A CVE can affect several teams; team totals are not additive.</span><button class="link small" data-action="active-inventory">All vulnerabilities →</button></div></section>
 <section class="panel"><div class="panel-head"><div><h2>Focus next</h2><p>A short, actionable queue.</p></div><span class="tag">Prioritized</span></div><div class="attention-list">
 <div class="attention-item"><div class="number">${u.length}</div><div><h3>Respond to P1 findings</h3><p>Review evidence, scope and the current plan.</p></div><button class="icon quiet" data-action="urgent-inventory" aria-label="Open immediate-priority findings">${I.arrow}</button></div>
 <div class="attention-item"><div class="number warn">${expires.length}</div><div><h3>Exceptions expire within 7 days</h3><p>Renew with evidence or request remediation.</p></div><button class="icon quiet" data-action="exceptions" aria-label="Review expiring exceptions">${I.arrow}</button></div>
 <div class="attention-item"><div class="number warn">${unassigned.length}</div><div><h3>Affected scopes have no team</h3><p>Assign ownership before work gets lost.</p></div><button class="icon quiet" data-action="team-review" data-team="unassigned" aria-label="Review unassigned findings">${I.arrow}</button></div>
 <div class="attention-item"><div class="number warn">${stale.length}</div><div><h3>Deployment evidence is stale</h3><p>Check missing scans before judging current risk.</p></div><button class="icon quiet" data-action="data-health" aria-label="Investigate stale evidence">${I.arrow}</button></div>
 </div></section></div>
 <div class="dashboard-secondary"><section class="panel"><div class="panel-head"><h2>Priority findings</h2><button class="link small" data-action="urgent-inventory">Open priority view →</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Priority / advisory</th><th>Package</th><th>Team</th><th>Work status</th><th>Due</th></tr></thead><tbody>${a.slice().sort((x,y)=>x.priority-y.priority).slice(0,3).map(r=>`<tr><td><div class="row">${priorityBadge(r)}<button class="cve-link" data-action="inspect" data-id="${r.id}">${r.id}</button></div></td><td>${esc(r.pkg)}</td><td>${[...new Set(visibleScopes(r).map(s=>cap(s.team)))].join(', ')}</td><td>${aggregateState(visibleScopes(r))}</td><td class="${new Date(r.due)<DEMO_NOW?'red':''}">${shortDate(r.due)}</td></tr>`).join('')}</tbody></table></div></section>
 <section class="panel"><div class="panel-head"><h2>Evidence health</h2><button class="link small" data-action="data-health">Details →</button></div><div class="panel-body" style="padding-top:5px;padding-bottom:5px"><div class="evidence-row"><span class="label">Latest sample import</span><span class="value">Today, 09:42 UTC</span></div><div class="evidence-row"><span class="label">Stale deployment scopes</span><span class="value ${stale.length?'amber':''}">${stale.length} of ${as.length}</span></div><div class="evidence-row"><span class="label">Public intelligence</span><span class="value amber">Sample cache only</span></div><div class="evidence-row"><span class="label">External integrations</span><span class="muted">Not connected</span></div></div></section></div>`;
}
function filteredInventory(){let rs=relevant().filter(r=>!state.query||[r.id,r.pkg,...visibleScopes(r).map(s=>s.service)].join(' ').toLowerCase().includes(state.query.toLowerCase()));if(state.severity!=='all')rs=rs.filter(r=>r.severity===state.severity);rs=rs.filter(r=>state.inventoryView==='all'||state.inventoryView==='active'&&visibleScopes(r).some(activeScope)||state.inventoryView==='accepted'&&visibleScopes(r).some(s=>s.status==='accepted')||state.inventoryView==='history'&&visibleScopes(r).some(s=>!activeScope(s))||state.inventoryView==='urgent'&&r.priority===1&&visibleScopes(r).some(activeScope)||state.inventoryView==='unknown'&&visibleScopes(r).some(s=>activeScope(s)&&s.exposure==='Unknown'));return rs.sort((a,b)=>state.sort==='age'?age(b)-age(a):a.priority-b.priority||a.id.localeCompare(b.id));}
function renderInventory(){const rs=filteredInventory(),selected=[...state.checked].filter(id=>rs.some(r=>r.id===id));return `<div class="page-head"><div><h1>Vulnerabilities</h1><p>One advisory per row. Open a finding without losing your place.</p></div><div class="row"><button data-action="density">${state.compact?'Comfortable':'Compact'} rows</button><button data-action="export">Export view</button></div></div><section class="panel"><div class="tabs" aria-label="Inventory views">${[['active','Active'],['accepted','Risk accepted'],['history','Observation history'],['all','All']].map(([k,l])=>`<button data-action="inventory-view" data-view="${k}" class="${state.inventoryView===k?'active':''}">${l}</button>`).join('')}${['urgent','unknown'].includes(state.inventoryView)?`<button class="active" data-action="inventory-view" data-view="${state.inventoryView}">${state.inventoryView==='urgent'?'P1 priority':'Unknown exposure'}</button>`:''}</div>
 <div class="toolbar"><div class="search">${I.search}<input id="inventorySearch" type="search" placeholder="Search CVE, package or service…" aria-label="Search vulnerabilities" value="${esc(state.query)}"></div><label><span class="sr-only">Scanner severity</span><select id="severityFilter"><option value="all">All severities</option>${['Critical','High','Medium','Low'].map(s=>`<option ${state.severity===s?'selected':''}>${s}</option>`).join('')}</select></label><label><span class="sr-only">Sort order</span><select id="sortFilter"><option value="priority" ${state.sort==='priority'?'selected':''}>Priority first</option><option value="age" ${state.sort==='age'?'selected':''}>Oldest first seen</option></select></label><span class="spacer"></span><button class="quiet" data-action="save-view">Save view</button><button class="quiet" data-action="saved-views">Saved views</button></div>
 ${selected.length?`<div class="batchbar"><strong>${selected.length} CVEs selected</strong><span class="spacer"></span><button data-action="batch-review">Review selected</button><button data-action="export-selected">Export selected</button><button data-action="clear-selection">Clear</button></div>`:`<div class="filter-summary"><strong>${rs.length} matching CVEs</strong><span>·</span><span>${state.team==='all'?'All teams':cap(state.team)}</span><span>·</span><span>${state.env==='all'?'All environments':cap(state.env)}</span><span class="spacer"></span><span>Reference advisories excluded</span></div>`}
 <div class="table-wrap"><table class="data-table"><caption class="sr-only">Vulnerabilities with priority, package, ownership, exposure and work status</caption><thead><tr><th><input type="checkbox" id="selectAll" aria-label="Select all matching CVEs" ${rs.length&&selected.length===rs.length?'checked':''}></th><th>Advisory / package</th><th>Severity</th><th>Priority</th><th>Affected</th><th>Exposure</th><th>Work status</th><th>Age</th><th>Fix info</th><th><span class="sr-only">Open detail</span></th></tr></thead><tbody>${rs.map(r=>{const ss=visibleScopes(r),teams=[...new Set(ss.map(s=>cap(s.team)))],exps=[...new Set(ss.map(s=>s.exposure))];return `<tr class="${state.checked.has(r.id)?'selected':''}"><td><input type="checkbox" class="row-check" data-id="${r.id}" aria-label="Select ${r.id}" ${state.checked.has(r.id)?'checked':''}></td><td><button class="cve-link" data-action="inspect" data-id="${r.id}">${r.id}</button><span class="subline">${esc(r.pkg)}${r.reopened?' · Re-observed':''}${ss.some(s=>s.suppressed)?' · Scanner suppression':''}</span></td><td>${severityBadge(r.severity)}</td><td>${priorityBadge(r)}</td><td>${teams.join(', ')}<span class="subline">${ss.length} ${ss.length===1?'scope':'scopes'}</span></td><td class="${exps.includes('Unknown')?'amber':''}">${exps.length===1?exps[0]:'Mixed'}${ss.some(s=>s.stale)?'<span class="subline amber">Evidence stale</span>':''}</td><td>${aggregateState(ss)}</td><td class="num">${age(r)}d</td><td>${r.fix?'<span class="blue">Available</span>':'<span class="muted">Not reported</span>'}</td><td><button class="icon quiet" data-action="inspect" data-id="${r.id}" aria-label="Open ${r.id}">${I.arrow}</button></td></tr>`}).join('')}</tbody></table>${!rs.length?empty('No matching vulnerabilities','Try another team, environment, or search. This is a filtered empty view, not evidence of safety.'):''}</div><div class="panel-foot"><span>${rs.length} of ${relevant().length} CVEs in shared scope · full matching set shown</span><span>Fix available ≠ fix deployed</span></div></section>`}
function empty(title,msg){return `<div class="empty"><h2>${title}</h2><p>${msg}</p><button data-action="reset-filters">Reset filters</button></div>`}
function queueRecords(){let rs=relevant().filter(r=>visibleScopes(r).some(s=>state.queueView==='needs_review'?attentionScope(s):state.queueView==='planned'?['planned','verification'].includes(s.status):state.queueView==='accepted'?s.status==='accepted':true));if(state.query)rs=rs.filter(r=>(r.id+' '+r.pkg).toLowerCase().includes(state.query.toLowerCase()));if(state.batchIds)rs=rs.filter(r=>state.batchIds.includes(r.id));return rs.sort((a,b)=>a.priority-b.priority||a.id.localeCompare(b.id));}
function getDraft(r){if(!drafts[r.id])drafts[r.id]={action:'planned',reason:'',owner:'',due:'2026-09-26',scopes:visibleScopes(r).filter(s=>activeScope(s)&&(state.queueView==='needs_review'?attentionScope(s):state.queueView==='accepted'?s.status==='accepted':state.queueView==='planned'?['planned','verification'].includes(s.status):true)).map(s=>s.id),send:false};let d=drafts[r.id];d.scopes=d.scopes.filter(id=>r.scopes.some(s=>s.id===id)&&visibleScopes(r).some(s=>s.id===id));return d;}
function renderReview(){let rs=queueRecords();let r=rs.find(r=>r.id===state.selected)||rs[0];if(r)state.selected=r.id;const d=r?getDraft(r):null;return `<div class="page-head"><div><h1>Review</h1><p>Evidence, affected scopes and a decision — in one workspace.</p></div><div class="row"><button data-action="review-history">Decision history</button><button data-action="density">${state.compact?'Comfortable':'Compact'} rows</button></div></div>
 <div class="review-tools"><div class="tabs" aria-label="Review work queues">${[['needs_review','Needs decision'],['planned','In progress'],['accepted','Exceptions'],...(state.queueView==='all'?[['all','All scoped items']]:[])].map(([k,l])=>`<button class="${state.queueView===k?'active':''}" data-action="queue-view" data-view="${k}">${l}</button>`).join('')}</div><button class="quiet queue-toggle" data-action="toggle-queue" style="display:none">${state.queueShown?'Assessment':'Queue'}</button>${state.batchIds?'<button class="quiet" data-action="clear-batch">Clear selected-only view</button>':''}<div class="search">${I.search}<input id="reviewSearch" type="search" placeholder="Find in queue…" aria-label="Search review queue" value="${esc(state.query)}"></div></div>
 <div class="review-grid"><section class="panel queue-panel" aria-label="Review queue"><div class="queue-heading"><strong>${rs.length} CVEs</strong><span class="muted small">Priority first</span></div><div class="queue-list">${rs.map(x=>`<button class="queue-item ${r?.id===x.id?'active':''}" data-action="select-review" data-id="${x.id}" ${r?.id===x.id?'aria-current="true"':''}><div class="row"><span class="queue-id grow">${x.id}</span>${priorityBadge(x)}</div><div class="queue-package">${esc(x.pkg)} <span class="muted">· ${x.severity}</span></div><div class="between queue-meta"><span>${[...new Set(visibleScopes(x).map(s=>cap(s.team)))].join(', ')} · ${visibleScopes(x).length} scopes</span>${new Date(x.due)<DEMO_NOW?'<span class="due">Overdue</span>':''}</div></button>`).join('')}${!rs.length?'<div class="empty"><p>No items in this queue.</p></div>':''}</div></section>
 <section class="panel review-workspace" aria-label="Current assessment">${r?`<div class="review-heading"><div class="between"><div><div class="row"><h2>${r.id}</h2>${severityBadge(r.severity)}${priorityBadge(r)}</div><p class="subtitle">${esc(r.pkg)} · ${visibleScopes(r).length} scopes in view · ${visibleScopes(r).some(s=>s.stale)?'Some evidence stale':'Last observed today, 09:42 UTC'}</p></div><div class="row head-actions"><button class="quiet" data-action="inspect" data-id="${r.id}">Full evidence ↗</button><button class="icon quiet" data-action="prev-review" aria-label="Previous CVE">‹</button><button class="icon quiet" data-action="next-review" aria-label="Next CVE">›</button></div></div></div>
 <div class="review-content"><div class="evidence-column"><div class="policy-strip"><strong>${r.priority===1?'Respond now':r.priority===2?'Prioritize review':'Review in routine queue'}</strong><span class="grow">· sample policy P${r.priority}</span><button class="link" data-action="policy" style="font-size:11px;min-height:22px">Why?</button></div><div class="block-title"><h3>What matters</h3><span>Scanner + scoped evidence</span></div><p class="summary-copy">Synthetic vulnerability in <strong>${esc(r.pkg)}</strong>. Review the affected deployment context and choose the next step. Package and fix labels are illustrative, not upgrade guidance.</p>
 <div class="fact-grid"><dl class="fact"><dt>Exploitation intelligence</dt><dd class="${r.kev.startsWith('Listed')?'red':'amber'}">${r.kev}</dd></dl><dl class="fact"><dt>Scanner-reported fix</dt><dd>${r.fix?'Available · not verified deployed':'No fix recorded'}</dd></dl></div>
 <div class="divider"></div><div class="block-title"><h3>Affected scope</h3><span id="scopeCount">${d.scopes.length} selected</span></div><div class="table-wrap"><table class="scope-table"><caption class="sr-only">Choose the exact affected scopes for this decision</caption><thead><tr><th><span class="sr-only">Select</span></th><th>Team / environment</th><th>Service</th><th>Exposure</th></tr></thead><tbody>${visibleScopes(r).map(s=>`<tr><td><label><input class="scope-check" type="checkbox" value="${s.id}" aria-label="Include ${s.team} ${s.env} ${s.service}" ${d.scopes.includes(s.id)?'checked':''}><span class="sr-only">Select</span></label></td><td><strong>${cap(s.team)}</strong><br><span class="muted">${cap(s.env)}</span></td><td><span class="mono">${s.service}</span><br><small class="muted">${s.stale?'Last seen 09 Sep · stale':'Last seen today'}</small></td><td class="${s.exposure==='Unknown'?'amber':''}">${s.exposure}</td></tr>`).join('')}</tbody></table></div><div class="coverage-note">Selections are explicit. A decision never silently covers another team or environment.</div>
 <details><summary>Priority rationale & assumptions</summary><div class="reason"><span class="mark">!</span><span>${r.severity} scanner severity${r.kev.startsWith('Listed')?' · sample known-exploitation signal':''}.</span></div><div class="reason"><span class="mark neutral">?</span><span>${visibleScopes(r).some(s=>s.exposure==='Unknown')?'Exposure is unknown for at least one scope. This is not a safe state.':'Exposure evidence does not itself prove exploitability or compromise.'}</span></div>${visibleScopes(r).some(s=>s.suppressed)?'<div class="reason"><span class="mark neutral">!</span><span>Scanner suppression has no recorded approver or date. It is not an accepted-risk decision.</span></div>':''}
</details> <details><summary>Technical evidence & provenance</summary><p>All records in this prototype are synthetic. In production this section links image digest, package identity, comparable scan runs, exposure source, evidence time, and policy version.</p><p>Presence, scanner suppression, assessment and remediation are separate facts.</p></details><details><summary>AI assistance · not configured</summary><p>Optional advisory assistance belongs here, not in a mandatory step. A production request must show the provider and outbound evidence before confirmation. No AI call is made by this prototype.</p></details></div>
 <aside class="decision-column" aria-label="Decision form"><h3>Choose the next action</h3><p class="intro">Applies only to the checked scopes.</p><div class="scope-alert" id="decisionScopeLabel">${d.scopes.length} scoped deployments selected</div><label class="field">Decision<select id="decisionAction"><option value="planned" ${d.action==='planned'?'selected':''}>Request remediation</option><option value="investigating" ${d.action==='investigating'?'selected':''}>Investigate / gather evidence</option><option value="accepted" ${d.action==='accepted'?'selected':''}>Accept risk temporarily</option><option value="verification" ${d.action==='verification'?'selected':''}>Request verification</option></select></label><label class="field">${d.action==='accepted'?'Recorded by (self-declared)':'Owner / responsible person'}<input id="decisionOwner" value="${esc(d.owner)}" placeholder="Enter a responsible owner" autocomplete="off"></label><label class="field">${d.action==='accepted'?'Exception expiry (UTC, inclusive)':'Due date'}<input type="date" id="decisionDue" min="2026-09-19" value="${esc(d.due)}"></label><label class="field">${d.action==='accepted'?'Rationale & compensating controls':'Decision note'}<textarea id="decisionReason" placeholder="Record the reason and next step…">${esc(d.reason)}</textarea></label>
 ${d.action==='accepted'?'<div class="inline-notice">Accepting risk does not remove a finding or make it safe. The exception expires at the end of the chosen UTC day.</div>':'<div class="quiet-notice">This saves a local work decision. It does not mark the vulnerability fixed.</div>'}
 <div class="divider" style="margin:12px 0"></div><div class="between"><strong style="font-size:11px">Azure DevOps</strong><span class="tag">Not connected</span></div><p class="form-note">Local decisions work without a ticket connection. External ticket creation requires a separate preview and confirmation.</p><button class="quiet" data-action="ticket-preview" style="font-size:11px;padding-left:0">Preview sample ticket flow ↗</button><div id="formError" role="alert"></div></aside></div>
 <footer class="review-footer"><span class="save-state" id="draftState">${storageOK?'Draft saved locally · not submitted':'Draft in this session · not submitted'}</span><div class="row"><button class="secondary-save" data-action="save-decision">Save decision</button><button class="primary" data-action="save-next">Save & next ${I.arrow}</button></div></footer>`:`<div class="empty" style="grid-row:1/-1;align-self:center"><h2>No decisions waiting here</h2><p>There may still be open vulnerabilities or gaps in coverage. Change scope or open another queue.</p><button data-action="active-inventory">View active CVEs</button></div>`}</section></div>`}
function updateScopeCount(){let checks=[...document.querySelectorAll('.scope-check:checked')];let n=checks.length;for(let id of ['scopeCount','decisionScopeLabel']){let el=document.getElementById(id);if(el)el.textContent=id==='scopeCount'?n+' selected':n+' scoped deployments selected'}for(let b of document.querySelectorAll('[data-action="save-decision"],[data-action="save-next"]'))b.disabled=n===0;}
function captureDraft(){if(state.page!=='review'||!state.selected)return;let r=records.find(x=>x.id===state.selected);if(!r||!document.getElementById('decisionAction'))return;drafts[r.id]={action:document.getElementById('decisionAction').value,owner:document.getElementById('decisionOwner').value,reason:document.getElementById('decisionReason').value,due:document.getElementById('decisionDue').value,scopes:[...document.querySelectorAll('.scope-check:checked')].map(c=>c.value)};saveStorage();}
function prepareDecision(next){captureDraft();const r=records.find(x=>x.id===state.selected),d=drafts[r.id];let errs=[];if(!d.scopes.length)errs.push('Select at least one affected scope.');if(!d.owner.trim())errs.push('Enter the responsible owner or recorded-by name.');if(!d.reason.trim())errs.push('Record a short rationale.');if(!d.due||d.due<'2026-09-19')errs.push('Choose today or a future date.');if(errs.length){document.getElementById('formError').innerHTML='<div class="form-error">'+errs.map(esc).join('<br>')+'</div>';document.getElementById('formError').scrollIntoView({block:'nearest'});return;}if(d.action==='accepted'){showModal('Confirm scoped risk acceptance',`<p><strong>${r.id}</strong> · ${d.scopes.length} explicitly selected scopes</p><p>Risk remains recorded. This is a time-limited exception, not a verified fix.</p><table class="mini-table">${r.scopes.filter(s=>d.scopes.includes(s.id)).map(s=>`<tr><td>${cap(s.team)} / ${cap(s.env)}</td><td>${s.service}</td></tr>`).join('')}</table><p>Expires <strong>${shortDate(d.due)} 2026, 23:59:59 UTC</strong>. Attribution is self-declared in this no-sign-in prototype.</p><div class="quiet-notice">Only the synthetic local dataset will change. No real risk is accepted.</div>`,`<button data-action="close-modal">Cancel</button><button class="primary" data-action="confirm-decision" data-next="${next}">Confirm demo exception</button>`);return;}commitDecision(next)}
function commitDecision(next){const r=records.find(x=>x.id===state.selected),d=drafts[r.id];const queue=queueRecords(),ix=queue.findIndex(x=>x.id===r.id),nextId=queue[(ix+1)%Math.max(queue.length,1)]?.id;for(let s of r.scopes){if(!d.scopes.includes(s.id))continue;s.status=d.action;s.owner=d.owner.trim();s.reason=d.reason.trim();s.due=d.due;}const type=d.action==='accepted'?'accepted':'requested';r.events.push({...e(type,DEMO_NOW.toISOString(),`${statusLabel[d.action]} · ${d.scopes.length} selected scopes · ${d.owner.trim()} (self-declared demo operator)`),scope_ids:[...d.scopes]});audit.unshift({id:r.id,action:d.action,at:DEMO_NOW.toISOString(),scopes:[...d.scopes],owner:d.owner,reason:d.reason,due:d.due});delete drafts[r.id];saveStorage();closeModal();if(next)state.selected=nextId;render();toast(`Demo decision saved for ${d.scopes.length} scope${d.scopes.length===1?'':'s'}. Other scopes were not changed.`)}
function timelineRange(){let end=new Date('2026-09-19T23:59:59Z'),start=new Date('2026-06-29T00:00:00Z');if(state.weeks===4)start=new Date('2026-08-23T00:00:00Z');return{start,end,total:end-start}}
function timeEvents(){const{start,end}=timelineRange();return relevant().flatMap(r=>r.events.filter(ev=>!ev.scope_ids||ev.scope_ids.some(id=>visibleScopes(r).some(s=>s.id===id))).map(ev=>({...ev,id:r.id,pkg:r.pkg}))).filter(ev=>new Date(ev.date)>=start&&new Date(ev.date)<=end&&(state.eventFilter==='all'||state.eventFilter==='observations'&&['new','observed','absent','reobserved'].includes(ev.type)||state.eventFilter==='decisions'&&['accepted','requested','verified'].includes(ev.type))).sort((a,b)=>new Date(b.date)-new Date(a.date));}
function eventName(t){return({new:'First observed',observed:'Observed',reobserved:'Observed again',absent:'No longer observed',verified:'Remediation verified',accepted:'Risk accepted',requested:'Work decision'})[t]||t}
function renderTimeline(){const{start,end,total}=timelineRange();let rs=relevant().sort((a,b)=>a.priority-b.priority||a.id.localeCompare(b.id)),events=timeEvents();let display=state.timelineTab==='tracks'?renderTracks(rs,events,start,total):state.timelineTab==='log'?renderEventLog(events):renderHeatmap(events);return `<div class="page-head"><div><h1>Timeline</h1><p>Recorded observations and decisions. Gaps stay visible; fixes need evidence.</p></div><div class="row"><label><span class="sr-only">Timeline window</span><select id="windowFilter"><option value="12" ${state.weeks===12?'selected':''}>Last 12 weeks</option><option value="4" ${state.weeks===4?'selected':''}>Last 4 weeks</option></select></label><button data-action="export-events">Export events</button></div></div><section class="panel"><div class="between" style="border-bottom:1px solid var(--line)"><div class="tabs" style="border:0" aria-label="Timeline views">${[['tracks','CVE tracks'],['log','Event log'],['daily','Daily activity']].map(([k,l])=>`<button class="${state.timelineTab===k?'active':''}" data-action="timeline-tab" data-tab="${k}">${l}</button>`).join('')}</div><label style="margin-right:12px"><span class="sr-only">Event type</span><select id="eventFilter" style="font-size:12px" ${state.timelineTab==='daily'?'disabled':''}><option value="all" ${state.eventFilter==='all'?'selected':''}>All event types</option><option value="observations" ${state.eventFilter==='observations'?'selected':''}>Observations only</option><option value="decisions" ${state.eventFilter==='decisions'?'selected':''}>Decisions / verification</option></select></label></div>
 <div class="timeline-stats"><span><strong>${events.length}</strong>recorded events</span><span><strong>${new Set(events.filter(x=>x.type==='new').map(x=>x.id)).size}</strong>first-observed CVEs</span><span><strong>${events.filter(x=>x.type==='absent').length}</strong>no-longer-observed events</span><span><strong>${events.filter(x=>x.type==='reobserved').length}</strong>re-observations</span><span class="spacer"></span><span class="muted small">${shortDate(start)} – ${shortDate(end)} 2026 · UTC</span></div>
 <div class="legend"><span><i class="swatch" style="border-radius:50%"></i>Observation</span><span><i class="swatch again"></i>Re-observed</span><span><i class="swatch missing"></i>Not observed ≠ fixed</span><span><i class="swatch verified"></i>Verified remediation</span><span><i class="swatch" style="background:#b48018"></i>Risk acceptance</span><span><i class="swatch" style="background:white;border:1.5px solid #2554ce"></i>Work decision</span><span class="spacer"></span><span>Markers do not establish continuous presence</span></div>${display}<div class="time-chart-note"><span>${rs.length} CVE lanes in scope · scroll to inspect every lane</span><span>Shaded coverage gaps mean no recorded scan — never “safe”.</span></div></section>`}
function renderTracks(rs,events,start,total){const pos=d=>Math.min(99.8,Math.max(.7,100*(new Date(d)-start)/total));let labels=[0,.25,.5,.75,1].map((f,i)=>`<span style="left:${f*100}%">${i===4?'19 Sep · sample today':shortDate(new Date(+start+total*f))}</span>`).join('');let days=Math.ceil(total/86400000);return `<div class="timeline-chart" role="region" aria-label="CVE observation timeline" tabindex="0"><div class="time-header"><div class="lane-label">Advisory / severity</div><div class="time-labels">${labels}</div></div><div class="coverage-track"><div class="lane-label">Scan coverage · any scope</div><div class="coverage-cells">${Array.from({length:days},(_,i)=>{let date=new Date(+start+i*86400000).toISOString().slice(0,10);let has=relevant().some(r=>r.events.some(ev=>['new','observed','reobserved','absent'].includes(ev.type)&&ev.date.slice(0,10)===date));return `<span class="coverage-cell ${has?'scanned':''}" title="${date}: ${has?'some sample scopes scanned; not full coverage':'no scan recorded'}"></span>`}).join('')}</div></div>${rs.map(r=>`<div class="time-row"><div class="lane-label"><span class="badge ${r.severity.toLowerCase()}" aria-label="${r.severity}" style="font-size:9px;padding:1px 4px">${r.severity[0]}</span><button data-action="inspect" data-id="${r.id}">${r.id}</button></div><div class="track">${events.filter(ev=>ev.id===r.id).map(ev=>`<button class="event ${ev.type}" style="left:${pos(ev.date)}%" data-action="event-detail" data-id="${r.id}" title="${esc(eventName(ev.type)+' · '+dateTime(ev.date))}" aria-label="${esc(r.id+' '+eventName(ev.type)+' '+dateTime(ev.date))}"><span class="shape"></span></button>`).join('')}</div></div>`).join('')}</div>`}
function renderEventLog(events){return `<div class="table-wrap" style="max-height:calc(100dvh - 395px)"><table class="data-table"><caption class="sr-only">Accessible record of each event in the selected timeline</caption><thead><tr><th>Recorded at · UTC</th><th>Advisory</th><th>Event</th><th>Evidence / decision</th></tr></thead><tbody>${events.map(ev=>`<tr><td>${dateTime(ev.date)}</td><td><button class="cve-link" data-action="event-detail" data-id="${ev.id}">${ev.id}</button></td><td>${eventName(ev.type)}</td><td class="wrap-text" style="max-width:650px">${esc(ev.description)}</td></tr>`).join('')}</tbody></table>${!events.length?empty('No recorded events in this filter','No event is not the same as no vulnerability.'):''}</div>`}
function renderHeatmap(events){let{start,end}=timelineRange();let weeks=state.weeks,base=new Date(start);let count=new Map();for(let ev of events.filter(x=>x.type==='new')){let d=ev.date.slice(0,10);if(!count.has(d))count.set(d,new Set());count.get(d).add(ev.id)}let html='<span class="heat-label">Day</span>';for(let w=0;w<weeks;w++)html+=`<span class="heat-label">${shortDate(new Date(+base+w*7*86400000))}</span>`;for(let day=0;day<7;day++){html+=`<span class="heat-label">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][base.getUTCDay()===0?(day+6)%7:day]}</span>`;for(let w=0;w<weeks;w++){let date=new Date(+base+(w*7+day)*86400000),k=date.toISOString().slice(0,10),n=count.get(k)?.size||0,future=date>end,hasScan=relevant().some(r=>r.events.some(ev=>['new','observed','reobserved','absent'].includes(ev.type)&&ev.date.slice(0,10)===k));html+=`<button class="heat-cell ${future?'future':!hasScan?'unknown':''}" data-action="day-detail" data-date="${k}" title="${k}: ${future?'future':hasScan?n+' first-observed CVEs in this view':'no scan recorded'}" ${future?'disabled':''} style="${n?'background:#456ead;color:white;font-weight:700':''}">${future?'—':n||(!hasScan?'·':'0')}</button>`}}return `<div class="heatmap-area"><div class="between" style="margin-bottom:14px"><strong style="font-size:12px">First observed CVEs by recorded day</strong><span class="muted small">Not CVE publication dates</span></div><div class="heatmap" style="grid-template-columns:38px repeat(${weeks},minmax(27px,1fr))">${html}</div><p class="small muted" style="margin-top:14px">Number = distinct first-observed CVEs in this view. Hatched cell = no scan recorded. Zero = no first observations in a scanned day; not proof of safety.</p></div><div id="dayDetail" class="day-detail">Select a day to see its recorded events.</div>`}
function showInspector(id,tab='summary'){captureDraft();state.inspectorId=id;state.inspectorTab=tab;renderInspector();let dlg=document.getElementById('inspector');if(!dlg.open)dlg.showModal();}
function renderInspector(){let r=records.find(x=>x.id===state.inspectorId);if(!r)return;let scopes=visibleScopes(r);if(!scopes.length)scopes=r.scopes;document.getElementById('inspector').innerHTML=`<div class="inspector-layout"><header class="inspector-head"><div class="between"><div class="row"><span class="scope-label">Advisory inspector</span><span class="tag">Synthetic record</span></div><div class="row"><button class="icon quiet" data-action="expand-inspector" aria-label="Expand or restore inspector">${I.expand}</button><button class="icon quiet" data-action="close-inspector" aria-label="Close advisory inspector">${I.close}</button></div></div><h2 id="inspectorTitle">${r.id}</h2><div class="row">${severityBadge(r.severity)}${priorityBadge(r)}<span class="muted small">${esc(r.pkg)} · ${scopes.length} scopes in view</span></div></header><nav class="tabs" aria-label="Advisory detail sections">${[['summary','Summary'],['affected','Affected assets'],['history','History'],['evidence','Evidence']].map(([k,l])=>`<button data-action="inspector-tab" data-tab="${k}" class="${state.inspectorTab===k?'active':''}">${l}</button>`).join('')}</nav><div class="inspector-body">${inspectorContent(r,scopes)}</div><footer class="inspector-foot"><span class="muted small grow">Exact scope is selected before a decision.</span><button data-action="close-inspector">Close</button><button class="primary" data-action="review-inspected" data-id="${r.id}">Review this CVE ${I.arrow}</button></footer></div>`}
function inspectorContent(r,ss){if(state.inspectorTab==='summary')return `<div class="section"><h3>At a glance</h3><p>This sample record demonstrates an evidence-first CVE detail. It is not a verified advisory, a statement about your systems, or a package upgrade recommendation.</p></div><div class="facts"><dl class="fact"><dt>Latest known state</dt><dd>${ss.some(activeScope)?'Open in inventory':'No current observation'}</dd></dl><dl class="fact"><dt>Current work</dt><dd>${aggregateState(ss)}</dd></dl><dl class="fact"><dt>Recorded age</dt><dd>${age(r)} days</dd></dl><dl class="fact"><dt>Exploitation intelligence</dt><dd>${r.kev}</dd></dl><dl class="fact"><dt>Reported fix</dt><dd>${r.fix?'Available · not deployed':'Not reported'}</dd></dl><dl class="fact"><dt>Evidence freshness</dt><dd>${ss.some(s=>s.stale)?'Some scopes stale':'Sample import: today'}</dd></dl></div><div class="section"><h3>Recommended next step</h3><div class="note">${r.priority===1?'Immediate review is the sample policy outcome.':'Confirm affected scope and assign an owner.'} Priority is not proof of exploitability or compromise.</div></div><div class="section"><h3>Affected teams & environments</h3>${ss.map(s=>`<div class="evidence-row"><div class="grow"><strong>${cap(s.team)} · ${cap(s.env)}</strong><div class="small muted">${s.service}</div></div><span class="${s.exposure==='Unknown'?'amber':''}">${s.exposure}</span><span>${statusLabel[s.status]}</span></div>`).join('')}</div><div class="section"><h3>Data confidence</h3><p>Unknown exposure is explicit, scanner suppressions are separate from human exceptions, and the absence of an observation is not called “fixed”.</p></div>`;
 if(state.inspectorTab==='affected')return `<div class="section"><h3>Affected assets · ${ss.length} scopes</h3><p>Team, environment, image and package identity define what a decision covers.</p></div>${ss.map(s=>`<div class="panel" style="margin-bottom:12px"><div class="panel-head"><strong>${cap(s.team)} / ${cap(s.env)}</strong>${labelState(s.status)}</div><div class="panel-body"><div class="mono" style="overflow-wrap:anywhere">registry.sample/${s.service}:demo-1.0</div><div class="small muted" style="margin-top:4px">Image digest: sample-sha256-${s.id} · Package: ${esc(r.pkg)}</div><div class="row wrap" style="margin-top:12px"><span class="tag">${s.exposure} exposure</span><span class="tag">${s.stale?'Stale observation':'Latest sample import'}</span>${s.suppressed?'<span class="badge medium">Scanner-suppressed · author unknown</span>':''}</div><p class="small muted" style="margin-top:10px">Last observed ${dateTime(s.observed)}</p></div></div>`).join('')}`;
 if(state.inspectorTab==='history')return `<div class="section"><h3>Observation and decision history</h3><p>Actual recorded event times only. “Not observed” is distinct from verified remediation.</p></div>${[...r.events].sort((a,b)=>new Date(b.date)-new Date(a.date)).map(ev=>`<div class="history-entry"><time>${dateTime(ev.date)}</time><div><strong>${eventName(ev.type)}</strong><p>${esc(ev.description)}</p></div></div>`).join('')}<div class="note" style="margin-top:16px">No inferred continuous exposure, invented action date, or automatic repair timer.</div>`;
 return `<div class="section"><h3>Evidence & provenance</h3><p>These fields illustrate the evidence contract expected from the real application.</p></div><table class="data-table"><tbody><tr><td>Dataset</td><td>Synthetic deployment fixture</td></tr><tr><td>Source record</td><td class="mono">${r.id}</td></tr><tr><td>Observation recorded</td><td>19 Sep 2026, 09:42 UTC</td></tr><tr><td>Public intelligence</td><td>Sample state, no online lookup</td></tr><tr><td>Policy</td><td>Illustrative P1 / P2 / P3, not a full SSVC implementation</td></tr><tr><td>Suppression</td><td>${ss.some(s=>s.suppressed)?'Imported flag; no human approval assumed':'No imported suppression in this scope'}</td></tr><tr><td>Identity</td><td>Local operator, self-declared; no authentication</td></tr></tbody></table><div class="note" style="margin-top:18px">A production implementation must retain source, observed-at, ingested-at, scope and completeness. Unknown values must not be replaced with “no”, 0 or a guessed timestamp.</div>`;}
function showModal(title,body,footer){const dlg=document.getElementById('modal');dlg.innerHTML=`<div class="modal-head between"><h2 id="modalTitle">${title}</h2><button class="icon quiet" data-action="close-modal" aria-label="Close dialog">${I.close}</button></div><div class="modal-body">${body}</div><div class="modal-foot">${footer||'<button class="primary" data-action="close-modal">Done</button>'}</div>`;if(!dlg.open)dlg.showModal();}
function closeModal(){let d=document.getElementById('modal');if(d.open)d.close();}
function settings(){showModal('Data & settings',`<p>One home for imports, evidence freshness and optional integrations — not repeated setup banners on every page.</p><table class="mini-table"><tr><td>Workspace</td><td>Local · no sign-in</td></tr><tr><td>Dataset</td><td>Synthetic demo only</td></tr><tr><td>Azure DevOps</td><td>Not connected</td></tr><tr><td>AI assistance</td><td>Not configured</td></tr><tr><td>Public intelligence</td><td>No external fetching in prototype</td></tr><tr><td>Saved demo decisions</td><td>${audit.length}</td></tr></table><div class="quiet-notice">No credentials are needed for this file. Never put production tokens in this prototype.</div><div class="row" style="margin-top:15px"><button data-action="data-health">Evidence health</button><button data-action="reset-demo">Reset synthetic data</button></div>`)}
function dataHealth(){const ss=active().flatMap(r=>visibleScopes(r).filter(activeScope));showModal('Evidence health',`<p><strong>Confidence is limited, not “safe”.</strong> Current totals reflect the latest recorded state of the selected deployment scopes.</p><table class="mini-table"><tr><td>Active scopes in view</td><td>${ss.length}</td></tr><tr><td>Exposure unknown</td><td>${ss.filter(s=>s.exposure==='Unknown').length}</td></tr><tr><td>Stale observation scopes</td><td>${ss.filter(s=>s.stale).length}</td></tr><tr><td>Latest sample import</td><td>19 Sep, 09:42 UTC</td></tr><tr><td>Reference advisories</td><td>Excluded from operational totals</td></tr><tr><td>Public intelligence cache</td><td>Sample data; not current intelligence</td></tr></table><p>Opening the application, changing filters or viewing evidence makes no network request. In production, an explicit import or confirmed refresh would update recorded coverage.</p>`)}
function policy(){showModal('Why this priority?',`<p><strong>P1 — respond now</strong>, <strong>P2 — prioritize review</strong>, and <strong>P3 — routine review</strong> are illustrative work priorities in this prototype. They do not replace the recorded scanner severity.</p><p>The intended production policy should show its version and the exact evidence that triggered the outcome: exploitation signal, affected deployment, exposure, consequence and deadline.</p><div class="quiet-notice">Unknown evidence never becomes a negative finding. “Internet exposed” is not proof of exploitability; “not listed” is not proof of no exploitation; a high work priority is not a compromise verdict.</div><p>These sample priorities are fixtures, not a validated threat model or a claim that the design implements SSVC.</p>`)}
function nextReview(delta){captureDraft();let rs=queueRecords();let i=rs.findIndex(r=>r.id===state.selected);if(rs.length){state.selected=rs[(i+delta+rs.length)%rs.length].id;state.queueShown=false;render();}}
function navigate(page){captureDraft();state.page=page;state.query='';state.checked.clear();if(page!=='review')state.batchIds=null;render();}
function reviewById(id){captureDraft();state.page='review';state.queueView='all';state.query='';state.batchIds=null;state.selected=id;state.queueShown=false;render();}
function goInventory(view){captureDraft();state.page='inventory';state.query='';state.inventoryView=view;state.checked.clear();render();}
function downloadJSON(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Synthetic filtered data exported.')}
let savedViews=[];try{savedViews=JSON.parse(localStorage.getItem(STORE_KEY+'-views')||'[]')}catch{}
function saveView(){showModal('Save this view',`<p>Stores team, environment, view, severity, search and sort locally.</p><label class="form-line">View name<input id="viewName" placeholder="For example, Production · P1" maxlength="80"></label>`,`<button data-action="close-modal">Cancel</button><button class="primary" data-action="confirm-save-view">Save view</button>`)}
function renderSavedViews(){showModal('Saved views',savedViews.length?savedViews.map((v,i)=>`<div class="evidence-row"><strong class="grow">${esc(v.name)}</strong><button data-action="load-view" data-index="${i}">Open view</button></div>`).join(''):'<p>No saved views yet. Use “Save view” after choosing your filters.</p>')}
function historyModal(){showModal('Decision history',audit.length?audit.map(a=>`<div class="history-entry"><time>${dateTime(a.at)}</time><div><strong>${a.id} · ${statusLabel[a.action]}</strong><p>${a.scopes.length} scope(s) · ${esc(a.owner)}</p><p>${esc(a.reason)}</p></div></div>`).join(''):'<p>No decisions have been recorded in this prototype yet.</p><p>Production should place all previous assessments here, preserving original scope and provenance rather than keeping a second competing review queue.</p>')}
function ticketPreview(){showModal('Azure DevOps ticket preview',`<div class="inline-notice">Integration not connected. This is a sample preview only; no ticket can be created.</div><p>Production flow: choose scoped decisions → resolve responsible teams → preview recipients and exact payload → explicitly confirm external creation.</p><table class="mini-table"><tr><td>Destination</td><td>Unconfigured</td></tr><tr><td>Outbound content</td><td>CVE + selected affected scopes + decision</td></tr><tr><td>Existing ticket matching</td><td>Required before creating duplicates</td></tr><tr><td>Ambiguous result</td><td>Reconcile before retrying</td></tr></table><p>The persistent review action saves locally and stays available even when Azure DevOps is not connected.</p>`,`<button data-action="close-modal">Back to review</button><button disabled>Create ticket · not connected</button>`)}
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-action]');if(!b||b.disabled)return;const act=b.dataset.action,id=b.dataset.id;
 switch(act){
 case'nav':navigate(b.dataset.page);break;
 case'settings':settings();break;case'data-health':dataHealth();break;case'policy':policy();break;
 case'reset-filters':captureDraft();state.team='all';state.env='all';state.query='';state.severity='all';state.inventoryView='active';state.batchIds=null;state.checked.clear();render();break;
 case'active-inventory':goInventory('active');break;case'urgent-inventory':goInventory('urgent');break;case'unknown-inventory':goInventory('unknown');break;
 case'start-review':captureDraft();state.page='review';state.query='';state.queueView='needs_review';state.batchIds=null;render();break;
 case'team-review':captureDraft();state.team=b.dataset.team;state.page='review';state.queueView='needs_review';state.query='';state.batchIds=null;render();break;
 case'team-inventory':state.team=b.dataset.team;goInventory('active');break;
 case'exceptions':captureDraft();state.page='review';state.queueView='accepted';state.query='';state.selected=null;render();break;
 case'inventory-view':state.inventoryView=b.dataset.view;state.checked.clear();render();break;
 case'inspect':showInspector(id);break;case'event-detail':showInspector(id,'history');break;
 case'close-inspector':document.getElementById('inspector').close();break;case'expand-inspector':document.getElementById('inspector').classList.toggle('expanded');break;
 case'inspector-tab':state.inspectorTab=b.dataset.tab;renderInspector();document.getElementById('inspector').querySelector(`[data-tab="${state.inspectorTab}"]`)?.focus();break;
 case'review-inspected':document.getElementById('inspector').close();reviewById(id);break;
 case'queue-view':captureDraft();state.queueView=b.dataset.view;state.batchIds=null;state.selected=null;render();break;
 case'select-review':captureDraft();state.selected=id;state.queueShown=false;render();break;
 case'toggle-queue':captureDraft();state.queueShown=!state.queueShown;render();break;
 case'next-review':nextReview(1);break;case'prev-review':nextReview(-1);break;
 case'save-decision':prepareDecision(false);break;case'save-next':prepareDecision(true);break;case'confirm-decision':commitDecision(b.dataset.next==='true');break;
 case'ticket-preview':captureDraft();ticketPreview();break;
 case'close-modal':closeModal();break;
 case'density':captureDraft();state.compact=!state.compact;render();break;
 case'export':downloadJSON({synthetic:true,scope:{team:state.team,env:state.env},records:filteredInventory().map(r=>({...r,scopes:visibleScopes(r)}))},'ptv-synthetic-view.json');break;
 case'export-selected':downloadJSON({synthetic:true,records:filteredInventory().filter(r=>state.checked.has(r.id)).map(r=>({...r,scopes:visibleScopes(r)}))},'ptv-synthetic-selected.json');break;
 case'export-events':downloadJSON({synthetic:true,events:timeEvents()},'ptv-synthetic-events.json');break;
 case'clear-selection':state.checked.clear();render();break;
 case'batch-review':state.batchIds=[...state.checked];state.page='review';state.queueView='all';state.selected=state.batchIds[0];render();break;
 case'clear-batch':captureDraft();state.batchIds=null;state.queueView='needs_review';render();break;
 case'timeline-tab':state.timelineTab=b.dataset.tab;if(state.timelineTab==='daily')state.eventFilter='observations';render();break;
 case'day-detail':{let day=b.dataset.date;let evs=timeEvents().filter(e=>e.date.slice(0,10)===day);let el=document.getElementById('dayDetail');if(el)el.innerHTML=`<strong>${shortDate(day)} 2026</strong> · ${evs.length} recorded events in this filter${evs.length?'<div class="row wrap" style="margin-top:8px">'+[...new Set(evs.map(x=>x.id))].map(id=>`<button class="link" data-action="event-detail" data-id="${id}">${id}</button>`).join('')+'</div>':'. No inference of safety.'}`;break;}
 case'save-view':saveView();break;case'saved-views':renderSavedViews();break;
 case'confirm-save-view':{let name=document.getElementById('viewName').value.trim();if(!name){document.getElementById('viewName').focus();return}savedViews.push({name,team:state.team,env:state.env,query:state.query,severity:state.severity,inventoryView:state.inventoryView,sort:state.sort});let persisted=true;try{localStorage.setItem(STORE_KEY+'-views',JSON.stringify(savedViews))}catch{persisted=false}closeModal();toast(persisted?'View saved in this browser.':'View saved for this session; browser storage is unavailable.');break;}
 case'load-view':{let v=savedViews[+b.dataset.index];if(v){Object.assign(state,{team:v.team,env:v.env,query:v.query,severity:v.severity,inventoryView:v.inventoryView,sort:v.sort,page:'inventory'});state.checked.clear();closeModal();render();}break;}
 case'review-history':historyModal();break;
 case'reset-demo':showModal('Reset synthetic data?',`<p>This removes only this prototype’s sample decisions, drafts and saved views from this browser. It has no connection to your real app.</p>`,`<button data-action="close-modal">Cancel</button><button class="primary" data-action="confirm-reset">Reset demo</button>`);break;
 case'confirm-reset':records=structuredClone(initial);drafts={};audit=[];savedViews=[];try{localStorage.removeItem(STORE_KEY+'-views')}catch{}closeModal();state.selected=null;state.checked.clear();saveStorage();render();toast('Synthetic data reset.');break;
 }
});
document.addEventListener('change',ev=>{const t=ev.target;if(t.id==='teamFilter'||t.id==='envFilter'){captureDraft();if(t.id==='teamFilter')state.team=t.value;else state.env=t.value;state.checked.clear();state.batchIds=null;render();return}if(t.id==='severityFilter'){state.severity=t.value;render()}if(t.id==='sortFilter'){state.sort=t.value;render()}if(t.id==='selectAll'){for(let r of filteredInventory())t.checked?state.checked.add(r.id):state.checked.delete(r.id);render()}if(t.classList.contains('row-check')){t.checked?state.checked.add(t.dataset.id):state.checked.delete(t.dataset.id);render()}if(t.classList.contains('scope-check')){captureDraft();updateScopeCount()}if(t.id==='decisionAction'){captureDraft();render()}if(t.id==='windowFilter'){state.weeks=+t.value;render()}if(t.id==='eventFilter'){state.eventFilter=t.value;render()}});
document.addEventListener('input',ev=>{const t=ev.target;if(t.id==='inventorySearch'||t.id==='reviewSearch'){const id=t.id,pos=t.selectionStart;captureDraft();state.query=t.value;render();let input=document.getElementById(id);input?.focus();try{input?.setSelectionRange(pos,pos)}catch{}}if(['decisionOwner','decisionDue','decisionReason'].includes(t.id)){captureDraft();let el=document.getElementById('draftState');if(el)el.textContent=storageOK?'Draft saved locally · not submitted':'Draft in this session only';}});
document.addEventListener('keydown',ev=>{const editing=ev.target.matches('input,textarea,select')||ev.target.isContentEditable;if(editing||document.querySelector('dialog[open]'))return;if(ev.key==='/'&&(state.page==='inventory'||state.page==='review')){ev.preventDefault();document.getElementById(state.page==='inventory'?'inventorySearch':'reviewSearch')?.focus()}if(state.page==='review'&&(ev.key==='j'||ev.key==='k')){ev.preventDefault();nextReview(ev.key==='j'?1:-1)}});
function initFromHash(){const p=new URLSearchParams(location.hash.slice(1));if(['overview','inventory','review','timeline'].includes(p.get('page')))state.page=p.get('page');if(['all','data','alpha','beta','platform','unassigned'].includes(p.get('team')))state.team=p.get('team');if(['all','prod','staging'].includes(p.get('env')))state.env=p.get('env');if(records.some(r=>r.id===p.get('item'))){state.selected=p.get('item');state.queueView='all';}}
initFromHash();render();
// Native dialogs supply modal focus containment and Escape dismissal. Return focus
// to a stable current control when a previously clicked opener was re-rendered.
for(const id of ['inspector','modal'])document.getElementById(id).addEventListener('close',()=>{if(document.activeElement===document.body)document.querySelector('#nav button.active')?.focus()});
