import Config

# Configure your database
config :triage, Triage.Repo,
  # Local PostgreSQL trusts the local `postgres` superuser; no password.
  # TRIAGE_DB_PORT selects a non-default local instance, such as the
  # Triage-owned development database from scripts/triage_dev_db.sh.
  # Absent keeps the historic default port.
  username: "postgres",
  hostname: "localhost",
  port: String.to_integer(System.get_env("TRIAGE_DB_PORT") || "5432"),
  database: "triage_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources. The Tailwind watcher rebuilds the stylesheet
# on source changes; it installs the CLI only if _build does not have it.
config :triage, TriageWeb.Endpoint,
  # runtime.exs enforces the TRIAGE_BIND loopback-only policy.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "hC4HG8qTPx98cDM7hNDMr99YeQiDagghonz1eg2a3fOjvc2Bba6nylEzo07tuORP",
  watchers: [
    tailwind: {Tailwind, :install_and_run, [:triage, ~w(--watch)]}
  ],
  # Refresh styles in already-open LiveViews without reloading the page or its draft.
  live_reload: [patterns: [~r"priv/static/assets/css/.*\.css$"]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :triage, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
