defmodule TriageWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :triage

  # Encrypt session contents as well as authenticating them. The eight-hour
  # lifetime is enforced by Plug's cookie verifier, not only by the browser.
  @session_options [
    store: :cookie,
    key: "_triage_key",
    signing_salt: "Cr6NkaDP",
    encryption_salt: "triage-session-v1",
    max_age: 28_800,
    http_only: true,
    secure: not code_reloading?,
    same_site: "Lax"
  ]

  # The serializer guard wraps only the V2 wire format to rewrite
  # malformed-query `url`s in socket payloads (see `TriageWeb.SocketSerializer`)
  # before the LiveView route decoder can crash the channel on them, so the
  # /live socket accepts vsn "2.0.0" only. LiveView's shipped JS hardcodes
  # vsn "2.0.0"; a client requesting an unmatched version (e.g. 1.0.0) is
  # refused at serializer negotiation with a logged warning and no channel,
  # rather than mounting an unguarded decoder path.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [session: @session_options],
      serializer: [{TriageWeb.SocketSerializer, "~> 2.0.0"}]
    ],
    longpoll: [
      connect_info: [session: @session_options],
      serializer: [{TriageWeb.SocketSerializer, "~> 2.0.0"}]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :triage,
    gzip: not code_reloading?,
    only: TriageWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :triage
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TriageWeb.Router
end
