defmodule Triage.Cases.CaseEvent do
  @moduledoc """
  Append-only audit trail of server-side case operations.

  Kinds are exactly `case_opened`, `evidence_captured` and `review_saved`:
  structural events generated by `Triage.Cases`, never free user text and
  never invented external approval/mitigation events. Rows are append-only,
  backed by PostgreSQL UPDATE/DELETE rejection triggers.
  """

  use Ecto.Schema

  schema "review_case_events" do
    field :case_id, :integer
    field :kind, :string
    field :case_revision, :integer
    field :snapshot_id, :integer
    field :review_id, :integer
    field :actor, :string
    field :detail, :map

    timestamps(type: :utc_datetime)
  end
end
