"""Interaction/layout regression tests for the offline synthetic prototype.
Run: python test_prototype.py (requires Playwright and a Chromium executable).
The test uses page.set_content, so persistence is tested as session fallback,
not as an assertion of durable localStorage on an actual file/HTTP origin.
"""
from pathlib import Path
import json, shutil
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).parent
HTML=(ROOT/'ptv-triage-prototype.html').read_text()
results=[]
def record(name,condition,detail=''):
    results.append({'test':name,'passed':bool(condition),'detail':detail})
    if not condition: raise AssertionError(name+': '+detail)

with sync_playwright() as pw:
    browser=pw.chromium.launch(headless=True,executable_path=shutil.which('chromium'),args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1600,'height':1000},device_scale_factor=1)
    page.set_default_timeout(4000)
    errors=[];network=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:network.append(r.url))
    page.set_content(HTML,wait_until='domcontentloaded')
    record('Initial dashboard totals are derived and correct',page.locator('.metric .value').all_text_contents()==['18','12','3','10'])
    page.screenshot(path=str(ROOT/'previews/01-overview.png'))
    page.select_option('#teamFilter','data')
    record('Team filter updates overview',page.locator('.metric .value').all_text_contents()==['4','1','1','1'])
    page.select_option('#envFilter','prod')
    record('Environment filter narrows affected scopes',page.evaluate('active().flatMap(r=>visibleScopes(r).filter(activeScope)).length')==3)
    page.locator('[data-action="reset-filters"]').click()
    page.locator('[data-action="urgent-inventory"]').first.click()
    record('P1 card drills into precisely matching CVEs',page.locator('.row-check').count()==3)
    page.locator('[data-action="inventory-view"][data-view="active"]').click()
    page.fill('#inventorySearch','ZLIB')
    record('Search is case insensitive and filters records',page.locator('.row-check').count()==1)
    page.fill('#inventorySearch','not-a-real-package')
    record('Filtered-empty state is explicit',page.locator('.empty').count()==1)
    page.fill('#inventorySearch','')
    page.screenshot(path=str(ROOT/'previews/03-inventory.png'))
    page.locator('.cve-link').first.click()
    record('Inspector opens with persistent review action',page.locator('#inspector').evaluate('(x)=>x.open') and page.locator('[data-action="review-inspected"]').is_visible())
    for tab in ['affected','history','evidence','summary']:
        page.locator(f'#inspector [data-tab="{tab}"]').click()
        record(f'Inspector {tab} content works',len(page.locator('.inspector-body').inner_text())>100)
    page.locator('[data-action="expand-inspector"]').click()
    record('Inspector expands',page.locator('#inspector').bounding_box()['width']>1000)
    page.locator('[data-action="expand-inspector"]').click()
    page.screenshot(path=str(ROOT/'previews/04-inspector.png'))
    page.keyboard.press('Escape')
    record('Escape dismisses inspector',not page.locator('#inspector').evaluate('(x)=>x.open'))
    page.locator('.row-check').nth(0).check()
    page.locator('.row-check').nth(1).check()
    record('Batch selection is explicit',page.locator('.batchbar strong').inner_text()=='2 CVEs selected')
    page.locator('[data-action="batch-review"]').click()
    record('Batch review retains exact selected CVEs',page.locator('.queue-item').count()==2)
    page.locator('[data-action="clear-batch"]').click()
    page.locator('[data-action="select-review"][data-id="DEMO-2026-001"]').click()
    page.screenshot(path=str(ROOT/'previews/02-review.png'))
    page.locator('[data-action="save-decision"]').click()
    record('Missing decision details show validation errors',page.locator('.form-error').count()==1)
    page.fill('#decisionOwner','Demo operator')
    page.fill('#decisionReason','Assign scoped remediation in this synthetic example.')
    page.locator('.scope-check[value="s02"]').uncheck()
    record('Explicit scope count updates',page.locator('#scopeCount').inner_text()=='1 selected')
    page.locator('[data-action="save-decision"]').click()
    record('Only selected scope changes',page.evaluate("records[0].scopes[0].status==='planned' && records[0].scopes[1].status==='needs_review'"))
    record('A work decision never fixes the observed vulnerability',page.evaluate('active().length')==18)
    record('Partial decisions retain remaining review work',page.evaluate('needs().length')==12)
    page.select_option('#decisionAction','accepted')
    page.fill('#decisionOwner','Demo operator')
    page.fill('#decisionReason','Scoped temporary acceptance for prototype test only.')
    page.locator('[data-action="save-decision"]').click()
    record('Risk acceptance requires explicit confirmation',page.locator('#modal').evaluate('(x)=>x.open'))
    page.locator('#modal [data-action="close-modal"]').last.click()
    record('Cancelling acceptance makes no state change',page.evaluate("records[0].scopes[1].status==='needs_review'"))
    page.locator('[data-action="save-decision"]').click()
    page.locator('[data-action="confirm-decision"]').click()
    record('Scoped acceptance leaves vulnerability active',page.evaluate("records[0].scopes[1].status==='accepted' && active().length===18 && needs().length===11"))
    record('Decision audit retains exact scope IDs',page.evaluate("audit[0].scopes.length===1&&audit[0].scopes[0]==='s02'"))
    # Reset before reference screenshots and responsive smoke tests.
    page.evaluate('records=structuredClone(initial);drafts={};audit=[];state.selected=null;render()')
    page.locator('[data-action="nav"][data-page="timeline"]').click()
    record('Timeline does not silently cap CVE lanes',page.locator('.time-row').count()==20)
    page.screenshot(path=str(ROOT/'previews/05-timeline.png'))
    page.locator('.event').first.click()
    record('Timeline marker opens same inspector on history',page.locator('#inspector [data-tab="history"]').get_attribute('class')=='active')
    page.keyboard.press('Escape')
    page.select_option('#windowFilter','4')
    record('Timeline window narrows real event range',page.evaluate("timeEvents().every(e=>new Date(e.date)>=new Date('2026-08-23'))"))
    page.select_option('#windowFilter','12')
    page.locator('[data-action="timeline-tab"][data-tab="daily"]').click()
    record('Future heatmap day is not shown as zero',page.locator('.heat-cell.future').count()==1 and page.locator('.heat-cell.future').inner_text()=='—')
    record('Unknown coverage days are visibly distinct',page.locator('.heat-cell.unknown').count()>0)
    page.locator('.heat-cell:not(.future)').first.click()
    record('Day drilldown is interactive','2026' in page.locator('#dayDetail').inner_text())
    page.locator('[data-action="timeline-tab"][data-tab="log"]').click()
    record('Accessible event log provides all events',page.locator('.data-table tbody tr').count()==page.evaluate('timeEvents().length'))
    # Save-view behavior is session-backed in this test origin.
    page.locator('[data-action="nav"][data-page="inventory"]').click()
    page.select_option('#severityFilter','High')
    page.locator('[data-action="save-view"]').click()
    page.fill('#viewName','High-priority sample view')
    page.locator('[data-action="confirm-save-view"]').click()
    page.select_option('#severityFilter','all')
    page.locator('[data-action="saved-views"]').click()
    page.locator('[data-action="load-view"]').click()
    record('Saved view restores filter state in-session',page.locator('#severityFilter').input_value()=='High')
    page.locator('[data-action="reset-filters"]').click()
    for width,height in [(1920,1080),(1600,900),(1440,900),(1366,768),(1280,720),(1024,768),(768,1024),(640,900),(390,844)]:
        page.set_viewport_size({'width':width,'height':height})
        page.evaluate("state.page='review';state.queueView='needs_review';state.selected='DEMO-2026-001';state.queueShown=false;render()")
        bounds=page.locator('[data-action="save-next"]').bounding_box()
        record(f'Review Save & next is on-screen at {width}x{height}',bounds is not None and bounds['y']>=0 and bounds['y']+bounds['height']<=height-22 and bounds['x']>=0 and bounds['x']+bounds['width']<=width, str(bounds))
        record(f'No document-wide horizontal overflow at {width}px',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        page.locator('[data-action="inspect"]').first.click()
        bounds=page.locator('[data-action="review-inspected"]').bounding_box()
        record(f'Inspector actions on-screen at {width}x{height}',bounds['y']+bounds['height']<=height and bounds['x']+bounds['width']<=width)
        page.keyboard.press('Escape')
        if width==1366:page.screenshot(path=str(ROOT/'previews/06-review-laptop.png'))
        if width==390:page.screenshot(path=str(ROOT/'previews/07-review-mobile.png'))
    record('No JavaScript runtime errors',not errors,str(errors))
    record('Prototype makes no network requests',not network,str(network))
    browser.close()

(ROOT/'test-results.json').write_text(json.dumps(results,indent=2))
print(json.dumps({'passed':sum(x['passed'] for x in results),'total':len(results)},indent=2))
