// CDP probe. Requires workspace_browser.exs's generated loopback origin.
const info = await pageInfo();
if (!globalThis.workspaceFixtureOrigin || new URL(info.url).origin !== globalThis.workspaceFixtureOrigin || !/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(globalThis.workspaceFixtureOrigin)) throw Error("Set workspaceFixtureOrigin to the owned fixture server origin");
const fs = await import("node:fs/promises");
const out = globalThis.workspaceEvidenceDir;
if (!out) throw Error("Set workspaceEvidenceDir");
const read = async expression => {const r=await session.Runtime.evaluate({expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const wait = expression => read(`new Promise((resolve,reject)=>{const check=()=>{if(${expression}){observer.disconnect();clearTimeout(timer);resolve(true)}};const observer=new MutationObserver(check);observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true});const timer=setTimeout(()=>{observer.disconnect();reject(new Error("Readiness timeout"))},5000);check();})`);
const click = selector => read(`document.querySelector(${JSON.stringify(selector)}).click()`);
const capture = async name => fs.writeFile(`${out}/${name}.png`,Buffer.from((await session.Page.captureScreenshot({format:"png"})).data,"base64"));
await session.Emulation.setDeviceMetricsOverride({width:1600,height:1000,deviceScaleFactor:1,mobile:false});
await session.Page.navigate({url:globalThis.workspaceFixtureOrigin+"/workspace?team=alpha&page=review"});
await wait('document.querySelector(".phx-connected #workspace-review")');
if (!await read('document.querySelector("#workspace-review").textContent.includes("Synthetic browser verification record.")')) throw Error("Not the owned synthetic fixture");
await capture("review-1600");
await read('document.querySelector(".review-heading a").focus()');
await click('.review-heading a');
await wait('document.querySelector("#workspace-inspector")?.open');
const collapsed = await read('document.querySelector("#workspace-inspector").getBoundingClientRect().width');
const tabs=[];
for (const tab of ["summary","assets","history","evidence"]) {
  await click(`#inspector-tab-${tab}`);
  await wait(`document.querySelector("#inspector-tab-${tab}").classList.contains("active")`);
  const scroll = await read('(()=>{const e=document.querySelector(".inspector-body");e.scrollTop=100000;return {overflow:getComputedStyle(e).overflowY,top:e.scrollTop,height:e.clientHeight,total:e.scrollHeight};})()');
  if(scroll.overflow!=="auto" || (scroll.total>scroll.height && scroll.top===0)) throw Error("Inspector body cannot scroll");
  const actions=await read('["#close-inspector","#expand-inspector","#inspector-review"].map(s=>{const e=document.querySelector(s),r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {s,visible:r.top>=0&&r.bottom<=innerHeight&&(h===e||e.contains(h))}})');
  if(actions.some(a=>!a.visible)) throw Error("Inspector actions obscured: "+tab);
  tabs.push({tab,actions});
  await capture(`inspector-${tab}-1600`);
}
await click('#expand-inspector');
await wait('document.querySelector("#workspace-inspector").classList.contains("expanded")');
const expanded = await read('document.querySelector("#workspace-inspector").getBoundingClientRect().width');
if(collapsed!==780 || expanded!==1240) throw Error("Inspector width mismatch");
for(const type of ["rawKeyDown","keyUp"]) await session.Input.dispatchKeyEvent({type,key:"Escape",code:"Escape",windowsVirtualKeyCode:27,nativeVirtualKeyCode:27});
await wait('!document.querySelector("#workspace-inspector")');
if (!await read('document.activeElement===document.querySelector(".review-heading a")')) throw Error("Focus did not return to inspector opener");
if (!await read('document.querySelector("#scope-target-1").checked')) await click('#scope-target-1');
await wait('document.querySelector("#scope-target-1").checked');
if (await read('document.querySelector("#scope-target-2").checked')) await click('#scope-target-2');
await wait('!document.querySelector("#scope-target-2").checked');
const due = new Date(Date.now()+7*86400000).toISOString().slice(0,10);
await read(`(()=>{const f=document.querySelector("#workspace-decision");for(const [k,v] of Object.entries({action:"accepted_risk",owner:"Browser owner",actor:"Browser reviewer",reason:"Production-only browser verification",due_on:${JSON.stringify(due)}})) f.elements["decision["+k+"]"].value=v;f.elements["decision[reason]"].dispatchEvent(new Event("input",{bubbles:true}));})()`);
await wait('document.querySelector("#shell").dataset.dirty==="true"');
await click('#save-decision');
await wait('document.querySelector("#risk-confirmation")?.open');
const confirmation = await read('(()=>{const r=document.querySelector("#risk-confirmation").getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,centered:Math.abs(r.x+r.width/2-innerWidth/2)<2&&Math.abs(r.y+r.height/2-innerHeight/2)<2};})()');
if(!confirmation.centered) throw Error("Confirmation is not centered");
await capture('acceptance-preview-1600');
await click('#cancel-risk');
await wait('!document.querySelector("#risk-confirmation")');
if(!await read('document.querySelector("#workspace-decision textarea").value==="Production-only browser verification"')) throw Error("Cancel lost draft");
await read('const a=document.querySelector(".decision-column select");a.value="request_remediation";a.dispatchEvent(new Event("change",{bubbles:true}));');
await click('#save-decision');
await wait('document.querySelector("#draft-state").textContent.includes("committed")');
const saved = await read('({cve:document.querySelector(".review-heading h2").textContent,targets:[...document.querySelectorAll(".scope-table tbody tr")].map(e=>e.textContent.trim()),dirty:document.querySelector("#shell").dataset.dirty})');
if(saved.cve!=="CVE-2099-1001"||!saved.targets[0].includes("Remediation requested")||!saved.targets[1].includes("Needs decision")||saved.dirty!=="false") throw Error("Scoped save failed "+JSON.stringify(saved));
await session.Page.reload({ignoreCache:true});
await wait('document.querySelector(".scope-table tbody tr")?.textContent.includes("Remediation requested")');
const result={tabs,collapsed,expanded,escape:true,focusReturn:true,cancelPreserved:true,saved,reloadPersisted:true};
await fs.writeFile(`${out}/interactions.json`,JSON.stringify(result,null,2));
return result;
